# 应用名称
spring:
  application:
    name: rabc
  datasource:
    url: jdbc:mysql://101.42.137.191:3306/lxh_645?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# 应用服务 WEB 访问端口
server:
  port: 80


mybatis:
  type-aliases-package: com.lxh.rabc.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
